### ISSUE TITLE
[BUG] Error while searching courses

### ISSUE THREAD

**Issue by sannibunny** [kentonlam/uqtp#3]
See screenshot below:

<img width="286" alt="Screen Shot 2021-02-15 at 6 04 16 pm" src="https://user-images.githubusercontent.com/47616667/107917466-16ae7980-6fbc-11eb-9256-40c899fe5bed.png">

**Comment by katrinafyi** [comment]
It looks like any search is rejecting with HTTP 500 and "Error occured while trying to proxy to: asia-northeast1-uq-toilet-paper.cloudfunctions.net/odd/rest/timetable/subjects". Likely an issue with the cloud function proxy.

**Comment by katrinafyi** [comment]
It was a GCP billing issue which should be fixed now. Logs show this started about 6 days ago.
